# Generated by Django 5.0.14 on 2026-08-25 14:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='ID da Conta (Open Finance)')),
                ('brand_name', models.CharField(max_length=80, verbose_name='Nome da Marca')),
                ('company_cnpj', models.CharField(max_length=14, verbose_name='CNPJ da Instituição')),
                ('type', models.CharField(choices=[('CONTA_DEPOSITO_A_VISTA', 'Conta de Depósito à Vista (Corrente)'), ('CONTA_POUPANCA', 'Conta Poupança'), ('CONTA_PAGAMENTO_PRE_PAGA', 'Conta de Pagamento Pré-Paga')], max_length=30, verbose_name='Tipo de Conta')),
                ('subtype', models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('CONJUNTA_SIMPLES', 'Conjunta Simples'), ('CONJUNTA_SOLIDARIA', 'Conjunta Solidária')], max_length=30, verbose_name='Subtipo de Conta')),
                ('number', models.CharField(max_length=20, verbose_name='Número da Conta')),
                ('branch_code', models.CharField(max_length=4, verbose_name='Código da Agência')),
                ('check_digit', models.CharField(max_length=2, verbose_name='Dígito Verificador')),
                ('currency', models.CharField(default='BRL', max_length=3, verbose_name='Moeda')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Conta',
                'verbose_name_plural': 'Contas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_amount', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='Saldo Disponível')),
                ('blocked_amount', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='Saldo Bloqueado')),
                ('automatically_invested_amount', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='Saldo Aplicado Automaticamente')),
                ('currency', models.CharField(default='BRL', max_length=3, verbose_name='Moeda')),
                ('update_date_time', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='balance', to='accounts.account', verbose_name='Conta')),
            ],
            options={
                'verbose_name': 'Saldo',
                'verbose_name_plural': 'Saldos',
            },
        ),
    ]
