# Generated by Django 5.0.14 on 2026-08-25 14:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='company_cnpj',
            field=models.CharField(max_length=14, validators=[django.core.validators.RegexValidator(message='CNPJ deve conter apenas números, com 14 dígitos.', regex='^\\d{14}$')], verbose_name='CNPJ da Instituição'),
        ),
        migrations.AlterField(
            model_name='balance',
            name='automatically_invested_amount',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Saldo Aplicado Automaticamente'),
        ),
        migrations.AlterField(
            model_name='balance',
            name='available_amount',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Saldo Disponível'),
        ),
        migrations.AlterField(
            model_name='balance',
            name='blocked_amount',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Saldo Bloqueado'),
        ),
    ]
