# Generated by Django 5.0.14 on 2026-08-25 14:08

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='ID da Transação (Open Finance)')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor da Transação')),
                ('currency', models.CharField(default='BRL', max_length=3, verbose_name='Moeda')),
                ('credit_debit_type', models.CharField(choices=[('CREDITO', 'Crédito (Entrada)'), ('DEBITO', 'Débito (Saída)')], max_length=10, verbose_name='Tipo de Lançamento (C/D)')),
                ('transaction_status', models.CharField(choices=[('LANCADO', 'Lançado'), ('PROCESSANDO', 'Processando')], default='LANCADO', max_length=15, verbose_name='Status da Transação')),
                ('transaction_date', models.DateField(verbose_name='Data da Transação')),
                ('transaction_date_time', models.DateTimeField(verbose_name='Data/Hora Completa da Transação')),
                ('transaction_type', models.CharField(choices=[('TED', 'TED'), ('DOC', 'DOC'), ('PIX', 'PIX'), ('BOLETO', 'Boleto Bancário'), ('TARIFAS', 'Tarifas'), ('ENCARGOS', 'Encargos'), ('DUPLICATA', 'Cobrança por Duplicata'), ('OPERACOES_CREDITO', 'Operações de Crédito'), ('OUTROS', 'Outros')], max_length=30, verbose_name='Tipo de Transação')),
                ('description', models.CharField(max_length=255, verbose_name='Descrição/Histórico')),
                ('payee_cnpj_cpf', models.CharField(blank=True, max_length=14, null=True, validators=[django.core.validators.RegexValidator(message='CPF ou CNPJ deve conter apenas números com 11 ou 14 dígitos.', regex='^(\\d{11}|\\d{14})$')], verbose_name='CPF/CNPJ do Favorecido/Pagador')),
                ('payee_name', models.CharField(blank=True, max_length=140, null=True, verbose_name='Nome do Favorecido/Pagador')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='accounts.account', verbose_name='Conta')),
            ],
            options={
                'verbose_name': 'Transação',
                'verbose_name_plural': 'Transações',
                'ordering': ['-transaction_date_time'],
                'indexes': [models.Index(fields=['account', '-transaction_date_time'], name='transaction_account_0fbf7b_idx')],
            },
        ),
    ]
