# Generated by Django 5.0.14 on 2026-08-25 14:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consent_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='ID do Consentimento (Open Finance)')),
                ('status', models.CharField(choices=[('AWAITING_AUTHORISATION', 'Aguardando Autorização'), ('AUTHORISED', 'Autorizado'), ('REJECTED', 'Rejeitado/Expirado'), ('REVOKED', 'Revogado')], default='AWAITING_AUTHORISATION', max_length=30, verbose_name='Status do Consentimento')),
                ('permissions', models.JSONField(verbose_name='Permissões de Acesso')),
                ('creation_date_time', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora de Criação')),
                ('expiration_date_time', models.DateTimeField(verbose_name='Data/Hora de Expiração')),
                ('status_update_date_time', models.DateTimeField(auto_now=True, verbose_name='Última Atualização de Status')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Consentimento',
                'verbose_name_plural': 'Consentimentos',
                'ordering': ['-creation_date_time'],
            },
        ),
    ]
